#!/bin/bash

alias ead="$EDITOR ~/dotfiles/shells/dockerfunc; source ~/dotfiles/shells/dockerfunc"

export docker_root_mount_path=${docker_root_mount_path:-${HOME}/projects}

alias d="docker"
alias dr="docker run -it --rm"

function dgcloud() {
        local cfgname=$(refresh-docker-kubeconfig /usr/bin/gcloud)
        trap "rm ${cfgname}" EXIT

        docker run --rm -it \
                -v "${HOME}/.config/gcloud:/.config/gcloud" \
                -v "${HOME}/.ssh:/root/.ssh:ro" \
                -v "$(which docker):/usr/bin/docker" \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v "${cfgname}:/.kube/config" \
                -v "${HOME}/.config/docker-kube:/.kube" \
                -v "${HOME}/.docker:/.docker" \
                -v "${docker_root_mount_path}/:${docker_root_mount_path}/" \
                -w $(pwd) \
                --user ${UID} \
                google/cloud-sdk:latest gcloud "$@"
}

function dkubectl() {
        local cfgname=$(refresh-docker-kubeconfig /usr/bin/gcloud)
        trap "rm ${cfgname}" EXIT

        docker run --rm -it \
                -v "${HOME}/.config/gcloud:/.config/gcloud" \
                -v "${cfgname}:/.kube/config" \
                -v "${docker_root_mount_path}/:${docker_root_mount_path}/" \
                -w $(pwd) \
                --user ${UID} \
                google/cloud-sdk:latest kubectl "$@"
}

function dhelm() {
        local docker_base_repo_url=${DOCKER_REGISTRY_PATH:-local}
        local cfgname=$(refresh-docker-kubeconfig)
        trap "rm ${cfgname}" EXIT

        docker run --rm -it \
                -v "${HOME}/.config/gcloud:/builder/home/.config/gcloud" \
                -v "${cfgname}:/builder/home/.kube/config" \
                -v "$HOME/.docker-data/helm/config:/builder/home/.config/helm" \
                -v "$HOME/.docker-data/helm/cache/repository:/builder/home/.cache/helm/repository" \
                -v "${docker_root_mount_path}/:${docker_root_mount_path}/" \
                -e HELM_REPO_UPDATE=no \
                -e TILLERLESS=${TILLERLESS} \
                -e HELM_REPO_DEFAULT_INIT=yes \
                -e HOME=/builder/home \
                --user ${UID} \
                -w $(pwd) \
                ${docker_base_repo_url}/helm "$@"
}

function dterraform() {
        local docker_base_repo_url=${DOCKER_REGISTRY_PATH:-local}
        local cfgname=$(refresh-docker-kubeconfig)
        trap "rm ${cfgname}" EXIT

        docker run --rm -it \
                -v "${HOME}/.ssh:/builder/home/.ssh:ro" \
                -v "$(which docker):/usr/bin/docker" \
                -v "/var/run/docker.sock:/var/run/docker.sock" \
                -v "${HOME}/.config/gcloud:/builder/home/.config/gcloud" \
                -v "${cfgname}:/builder/home/.kube/config" \
                -v "${docker_root_mount_path}/:${docker_root_mount_path}/" \
                -v "${HOME}/.vault-token:/builder/home/.vault-token" \
                -v "$HOME/.docker-data/helm/config:/builder/home/.config/helm" \
                -v "$HOME/.docker-data/helm/cache/repository:/builder/home/.cache/helm/repository" \
                -w $(pwd) \
                -e VAULT_ADDR=${VAULT_ADDR} \
                -e TF_INIT=no \
                -e TF_LOG="${TF_LOG}" \
                -e HOME=/builder/home \
                --user ${UID} \
                ${docker_base_repo_url}/terraform-helm "$@"
}

#--- helpers ----------------------------------------------
function refresh-docker-kubeconfig() {
        local gcloud_bin=${1:-/builder/google-cloud-sdk/bin/gcloud}
        local kubecfg=${HOME}/.kube/config

        if [[ ${KUBECONFIG} != "" ]]; then
                kubecfg=$KUBECONFIG
        fi

        local cfgname=$(mktemp ${TMPDIR}/kubeconfig.XXXXXX)

        if [[ $(uname -s) == "Darwin" ]]; then
                sed -e "s|/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud|${gcloud_bin}|g" ${kubecfg} >${cfgname}
        else
                cp ${kubecfg} ${cfgname}
        fi

        echo ${cfgname}
}
