#!/bin/bash
GPG_TTY=$(tty)
export GPG_TTY

if [[ $(uname) == "Darwin" ]]; then
        if [ -z "$GPG_AGENT_INFO" ]; then
                gpg-agent --daemon --enable-ssh-support
        fi
        if [ -S "${HOME}/.gnupg/S.gpg-agent.ssh" ]; then
                export SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh
        fi
fi

#vim: ft=sh
