#!/usr/bin/env bash

alias et="$EDITOR ~/dotfiles/shells/terraform; source ~/dotfiles/shells/terraform"

alias tf=dterraform

alias tfa="dterraform apply"
alias tfat="dterraform apply -target="
alias tfpt="dterraform plan -target="
