#!/usr/bin/env bash

alias et="$EDITOR ~/dotfiles/shells/terraform; source ~/dotfiles/shells/terraform"

alias tf=terraform

alias tfa="tf apply"
alias tfp="tf plan"
alias tfd="tf plan"
alias tfi="tf init"
alias tfsl="tf state list"

function tfat() {
        tf apply -target="$@"
}
function tfpt() {
        tf plan -target="$@"
}
function tfdt() {
        tf destroy -target="$@"
}
