#!/usr/bin/env bash

alias et="$EDITOR ~/dotfiles/shells/terraform; source ~/dotfiles/shells/terraform"

alias tf=dterraform

alias tfa="dterraform apply"
alias tfp="dterraform plan"
alias tfd="dterraform plan"
alias tfi="dterraform init"
alias tfsl="dterraform state list"

function tfat() {
        dterraform apply -target="$@"
}
function tfpt() {
        dterraform plan -target="$@"
}
function tfdt() {
        dterraform destroy -target="$@"
}
