[kubernetes]
symbol = "⛵ "
style = "bold blue"
disabled = false

[kubernetes.context_aliases]
"gke_labo-gke-237917_northamerica-northeast1_labo1" = "labo1"
"gke_devl-gke-230115_northamerica-northeast1_dev1" = "dev1"
"gke_infra-gke-251418_northamerica-northeast1_infra1" = "infra1"
"gke_prod-gke-230115_northamerica-northeast1_prod1" = "prod1"

[terraform]
format = "via [$symbol$version]($style) "

[gcloud]
disabled = true
symbol = " "

[line_break]
disabled = false

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
